// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBxaQ8iDRZErcLc8tSHvA9grLS-roIXELU',
    appId: '1:132582231310:web:1c1a01ab1fb34d1e639b5f',
    messagingSenderId: '132582231310',
    projectId: 'chatapp-d9109',
    authDomain: 'chatapp-d9109.firebaseapp.com',
    storageBucket: 'chatapp-d9109.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB-ubriwLmnqnkrMVyz5inFAzD9ldadcSg',
    appId: '1:132582231310:android:34058fd3c990a942639b5f',
    messagingSenderId: '132582231310',
    projectId: 'chatapp-d9109',
    storageBucket: 'chatapp-d9109.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDcyteIXa5qLCpmPVVhPTfpr-cA1YQtF6E',
    appId: '1:132582231310:ios:4cb6976f0fd75fac639b5f',
    messagingSenderId: '132582231310',
    projectId: 'chatapp-d9109',
    storageBucket: 'chatapp-d9109.appspot.com',
    iosBundleId: 'com.example.chatApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDcyteIXa5qLCpmPVVhPTfpr-cA1YQtF6E',
    appId: '1:132582231310:ios:55290aa347c526e7639b5f',
    messagingSenderId: '132582231310',
    projectId: 'chatapp-d9109',
    storageBucket: 'chatapp-d9109.appspot.com',
    iosBundleId: 'com.example.chatApp.RunnerTests',
  );
}
